packages:
  - apps/*
  - packages/*

catalog:
  "@vitest/coverage-v8": 4.1.4
  vite: 8.0.10
  vitest: 4.1.4

minimumReleaseAge: 10080

onlyBuiltDependencies:
  - "@swc/core"
  - esbuild
  - unrs-resolver
